
const galeries = [{ name: "Galeria LA Primera", street: "Bogotá ", number: "3465" },
{ name: "Galeria La Cueva", street: "Bogotá ", number: "3483" },
{ name: "Paseo de la Moda", street: "Bogotá ", number: "3375" },
{ name: "Paseo de la Luna", street: "Bogotá ", number: "3365" },
{ name: "Galeria Aventura Mall", street: "Bogotá ", number: "3355" },
{ name: "Galeria Aventura Mall 2", street: "Bogotá ", number: "3345" },
{ name: "Galeria La Soñada", street: "Bogotá ", number: "3291" },
{ name: "Galería Ocho del Ocho", street: "Bogotá 3263 y ", number: "3265" },
{ name: "Galería Poppy", street: "Bogotá ", number: "3259" },
{ name: "Galeria Calacoto", street: "Bogotá ", number: "3245" },
{ name: "Galería los Planetas", street: "Bogotá ", number: "3239" },
{ name: "Galería Paseo de las Estrellas", street: "Bogotá ", number: "3231" },
{ name: "Galería Camino de la Ciudad", street: "Bogotá ", number: "3219" },
{ name: "Galería La Maquinista", street: "Bogotá ", number: "3213" },
{ name: "Galería Punto Flores", street: "Bogotá ", number: "3173" },
{ name: "Galería La Elegida", street: "Bogotá ", number: "3165" },
{ name: "Galeria La Bolsa", street: "Bogotá ", number: "3155" },
{ name: "Galeria Broadway", street: "Bogotá ", number: "3075" },
{ name: "Galeria La Cascada", street: "Bogotá ", number: "3055" },
{ name: "Galería Macys", street: "Bogotá ", number: "3056" },
{ name: "Galería La Faiet", street: "Bogotá ", number: "3043" },
{ name: "Galería Las Palmeras", street: "Bogotá ", number: "3025" },
{ name: "Galería La Operá", street: "Bogotá ", number: "3009" },
{ name: "Galería Onda Mayorista", street: "Bogotá ", number: "3128" },
{ name: "Galería Smart Go", street: "Bogotá 2973 y ", number: "2975" },
{ name: "Galería Smart + Alta", street: "Bogotá ", number: "2963" },
{ name: "Galeria Smart + Alta", street: "Bogotá 2971   ", number: "1piso" },
{ name: "Galería Altos de Nazca", street: "Bogotá ", number: "2957" },
{ name: "Galeria Paseo De las Nubes", street: "Bogotá ", number: "2953" },
{ name: "Galería Smart Bogotá", street: "Bogotá ", number: "2947" },
{ name: "Galeria Adelita", street: "Bogotá ", number: "2935" },
{ name: "Galeria Paseo Continental", street: "Bogotá ", number: "2936" },
{ name: "Galería Arcos del Triunfo", street: "Bogotá ", number: "2940" },
{ name: "Galería Las Estrellas de Bogota", street: "Bogotá ", number: "2950" },
{ name: "Galería El Palacio de la Moda", street: "Bogotá ", number: "2956" },
{ name: "Galería Mogote Factory", street: "Bogotá  ", number: "2972" },
{ name: "Galería Macys", street: "Bogotá ", number: "3056" },
{ name: "Galeria de las Américas", street: "Bogotá ", number: "3080" },
{ name: "Galeria Acuarela", street: "Bogotá ", number: "3090" },
{ name: "Galeria Onda Mayorista ", street: "Bogotá ", number: "3128" },
{ name: "Galeria Shopping Buenos Aires", street: "Bogotá ", number: "3146" },
{ name: "Galeria Paseo Bogota", street: "Bogotá ", number: "3168" },
{ name: "Galería Centro Comercial Flores", street: "Bogotá ", number: "3172" },
{ name: "Galería  La Alegria", street: "Bogotá ", number: "3258" },
{ name: "Galeria Paseo del Sol", street: "Bogotá ", number: "3372" },

{ name: "Galería Bacacay", street: "Bacacay ", number: "3319" },
{ name: "Galeria Bacacay Center", street: "Bacacay ", number: "3221" },
{ name: "Galería Bacacay Plaza", street: "Bacacay ", number: "3326" },
{ name: "Galeria La Nacional", street: "Bacacay ", number: "3435" },
{ name: "Galeria Ecomoda", street: "Bacacay ", number: "3419" },
{ name: "Galería Paseo Paris ", street: "Bacacay ", number: "3359" },
{ name: "Galería La Huella", street: "Bacacay ", number: "3369" },
{ name: "Galería la Quinta Avenida", street: "Bacacay ", number: "3347" },
{ name: "Galeria Via Flores", street: "Bacacay ", number: "3231" },
{ name: "Galería  Paseo de Gracia", street: "Bacacay ", number: "3241" },
{ name: "Galeria Via Fores", street: "Bacacay ", number: "3231" },
{ name: "Galería Fabricantes Unidos", street: "Bacacay ", number: "3181" },
{ name: "Galería La Nueva Estrella", street: "Bacacay ", number: "3161" },
{ name: "Galeria Super Mayorista", street: "Bacacay ", number: "3129" },
{ name: "Galeria Misso", street: "Bacacay ", number: "3184" },
{ name: "Galeria Center 1", street: "Bacacay ", number: "3064" },
{ name: "Galería Premium Mall", street: "Bacacay ", number: "3065" },
{ name: "Galería La Pista", street: "Bacacay ", number: "2953" },
{ name: "Galeria Via Veneto", street: "Bacacay ", number: "2977" },
{ name: "Galeria  La Gran Via", street: "Bacacay ", number: "2932" },
{ name: "Galeria Paseo Imperial ", street: "Bacacay ", number: "2938" },
{ name: "Galería La Ribera", street: "Bacacay ", number: "2960" },
{ name: "Galería Outlet Flores", street: "Bacacay ", number: "2968" },
{ name: "Galeria Center", street: "Bacacay ", number: "3064" },
{ name: "Galeria Portal del Angel", street: "Bacacay ", number: "3156" },
{ name: "Galería Paseo Galxy", street: "Bacacay ", number: "3248" },
{ name: "Galeria las Chozas", street: "Bacacay ", number: "3474" },

{ name: "Galería La Gran Via", street: "Avellaneda ", number: "3727" },
{ name: "Galeria Paseo del Eclipse", street: "Avellaneda ", number: "3735" },
{ name: "Galeria Paseo los Leones", street: "Avellaneda ", number: "3683" },
{ name: "Galeria  3 elefante ", street: "Avellaneda ", number: "3671" },
{ name: "Galería Paseo de lo Astronautas", street: "Avellaneda ", number: "3508" },
{ name: "Galería EL CIEL ", street: "Avellaneda ", number: "3587" },
{ name: "GALERIA DE LA LUZ", street: "Avellaneda ", number: "3579" },
{ name: "Galería PASEO DEL COSMOS", street: "Avellaneda ", number: "3549" },
{ name: "Galeria Comercial 76 ", street: "Avellaneda ", number: "3264" },
{ name: "Galeria Gallery Express", street: "Avellaneda ", number: "3348" },
{ name: "Galeria Punto Avellaneda", street: "Avellaneda ", number: "2821" },
{ name: "Galeria Avellaneda", street: "Avellaneda ", number: "2771" },
{ name: "Galeria Paseo de las Galaxias", street: "Avellaneda ", number: "2763" },
{ name: "Galeria Shopping Mayorista Saint  Trope ", street: "Avellaneda  ", number: "3036" },
{ name: "Galería  Open Plaz ", street: "Avellaneda ", number: "3470" },
{ name: "Galería  MAAIA ", street: "Avellaneda ", number: "3484" },
{ name: "Galería MAMILA SHOPPING", street: "Avellaneda ", number: "3478" },
{ name: "Galería Paseo de los Astronautas", street: "Avellaneda ", number: "3510" },
{ name: "Galería Manhatta ", street: "Avellaneda ", number: "3578" },
{ name: "Galería Buenos Aires", street: "Avellaneda ", number: "3636" },
{ name: "Galería Paseo del Universo", street: "Avellaneda ", number: "3640" },
{ name: "Galería Paseo de Compras 366 ", street: "Avellaneda ", number: "3660" },
{ name: "Galeria Smart Go", street: "Avellaneda ", number: "2966" },
{ name: "Galería DAIS ", street: "Avellaneda ", number: "3550" },

{ name: "GALERIA SANTIAGO APOSTOL", street: "Joaquín Gonzalez ", number: "460" },
{ name: "Galería Copacabana", street: "Joaquín Gonzalez ", number: "465" },
{ name: "Galeria PASEO DE LOS COLORES", street: "Joaquín Gonzalez ", number: "456" },
{ name: "Galeria PASEO DEL ECLIPSE", street: "Joaquín Gonzalez ", number: "446" },

{ name: "Galeria  LOS ANDES ", street: "San nicolas ", number: "378" },
{ name: "GALERIA BUENOS AIRES", street: "San nicolas  ", number: "358" },

{ name: "Galería Las chozas", street: "Emilio lamarca ", number: "171" },
{ name: "Galeria Manhattan ", street: "Emilio lamarca ", number: "213" },
{ name: "Galería  Don Jorge", street: "Emilio lamarca ", number: "341" },
{ name: "Galeria  La Marca", street: "Emilio lamarca ", number: "343" },
{ name: "Galería La Bendecida", street: "Emilio lamarca ", number: "447" },
{ name: "Galería  El viejo taller", street: "Emilio lamarca  ", number: "461" },
{ name: "Galeria  La Gigante", street: "Concordia ", number: "135" },
{ name: "Galeria Paseo del Cielo", street: "Concordia ", number: "233" },
{ name: "Galería Pequeña Bolivia", street: "Concordia ", number: "271" },
{ name: "Galeria  La Bernabeu", street: "Concordia ", number: "321" },
{ name: "Galeria  De  La Moda", street: "Concordia ", number: "335" },
{ name: "Galería Centro Mayorista", street: "Concordia ", number: "341" },
{ name: "Galería Paseo Concordia", street: "Concordia ", number: "359" },
{ name: "Galería Centro Mayorista", street: "Concordia ", number: "360" },
{ name: "Galeria Gallery Center", street: "Concordia ", number: "344" },
{ name: "Galeria Plaza Concordia", street: "Concordia ", number: "260" },
{ name: "Galeria Paseo del Arco Iris", street: "Concordia ", number: "246" },
{ name: "Galería Alto Concordia ", street: "Concordia ", number: "232" },
{ name: "Galería Concordia", street: "Concordia ", number: "132" },
{ name: "Galería paseo de la Concorde", street: "Concordia ", number: "196" },
{ name: "Galeria  Neocampana", street: "Campana ", number: "237" },
{ name: "Galeria  Los Fabricantes", street: "Campana ", number: "243" },
{ name: "Galeria Tortuga", street: "Campana ", number: "255" },
{ name: "Galeria Comercial  La Colorada", street: "Campana ", number: "275" },
{ name: "Galeria Mundo Textil", street: "Campana ", number: "560" },
{ name: "Galería Smart Campana", street: "Campana ", number: "378" },
{ name: "Galeria del Norte", street: "Campana ", number: "358" },
{ name: "Galeria Campana Center", street: "Campana ", number: "276" },
{ name: "Galeria  Quela  Gus", street: "Campana ", number: "262" },
{ name: "Galeria Smart 3 Campanas", street: "Campana 242/", number: "252" },
{ name: "Galeria Super Campana", street: "Campana ", number: "230" },
{ name: "Galeria Ciudad Campana", street: "Campana ", number: "642" },
{ name: "Galería Fabricantes Unidos", street: "Cuenca ", number: "227" },
{ name: "Galeria Centro mayorista", street: "Cuenca ", number: "241" },
{ name: "Galería La divina", street: "Cuenca ", number: "245" },
{ name: "Galeria Cleopatra", street: "Cuenca ", number: "363" },
{ name: "Galeria los Visionarios", street: "Cuenca ", number: "648" },
{ name: "Galeria Lady Mall", street: "Cuenca ", number: "450" },
{ name: "Camino de la Ciudad", street: "Cuenca ", number: "330" },
{ name: "Galeria La Bonita", street: "Cuenca ", number: "290" },
{ name: "Galeria Comercial La violeta", street: "Cuenca ", number: "284" },
{ name: "Galeria El trébol", street: "Cuenca ", number: "262" },
{ name: "Galería La Gran Central", street: "Helguera ", number: "249" },
{ name: "Galería Helguera Place ", street: "Helguera ", number: "449" },
{ name: "Galeria Helguera Mall", street: "Helguera ", number: "454" },
{ name: "Galeria Sol del Norte", street: "Helguera ", number: "356" },
{ name: "Galeria  Berajá", street: "Helguera ", number: "280" },
{ name: "Galeria Las Palmeras", street: "Argerich ", number: "432" },
{ name: "Galería OXFORD", street: "Argerich ", number: "435" },
{ name: "Galeria Exito!!!", street: "Argerich ", number: "386" },
{ name: "Galeria Outle Flores", street: "Argerich ", number: "209" },
{ name: "Galeria Paseo del Corso", street: "Av. Nazca ", number: "55" },
{ name: "Galería Nazca", street: "Av. Nazca ", number: "150" },
{ name: "Galeria   La 27", street: "Av. Nazca ", number: "271" },
{ name: "Galería  Acasia", street: "Av. Nazca ", number: "357" },
{ name: "Galería aiwen", street: "Av. Nazca ", number: "363" },
{ name: "Galería La Hermandad", street: "Av. Nazca ", number: "453" },
{ name: "Galeria  KOAR", street: "Av. Nazca ", number: "566" },
{ name: "Galeria SHOPPING NAZCA", street: "Av. Nazca ", number: "544" },
{ name: "Galeria Punto Nazca", street: "Av. Nazca ", number: "466" },
{ name: "Galería Altos de Nazca", street: "Av. Nazca ", number: "420" },
{ name: "Galeria La Cumbre", street: "Av. Nazca ", number: "376" },
{ name: "Galeria Nazca", street: "Av. Nazca ", number: "366" },
{ name: "Galeria  FEM Baires", street: "Av. Nazca ", number: "358" },
{ name: "Galeria Internacional", street: "Av. Nazca ", number: "346" },
{ name: "Galeria  El Malecón", street: "Av. Nazca ", number: "322" },
{ name: "Galeria Milenium", street: "Av. Nazca ", number: "314" },
{ name: "Galeria   La Gran Esquina", street: "Av. Nazca ", number: "298" },
{ name: "Galeria  La Gran Via", street: "Av. Nazca ", number: "274" },
{ name: "Galería La hoja", street: "Av. Nazca ", number: "81" },
{ name: "Galeria Manantiales", street: "Av. Nazca ", number: "84" },
{ name: "Galeria Hollywood City", street: "Av. Nazca ", number: "60" },
{ name: "Galeria Paseo Italia", street: "Av. Nazca ", number: "50" },
{ name: "Halería Metro", street: "Av. Nazca ", number: "36" },
{ name: "Galeria Paseo De Compras Nazca", street: "Av. Nazca ", number: "2940" },

{ name: "Galería Mónaco", street: "Venecio flores ", number: "3029" },
{ name: "GALERÍA EL PUENTE", street: "Venecio flores ", number: "3055" },




{name: "willy", number: 2757, street: "Av. Rivadavia", location: "Once"},
{name: "Paseo del Once", number: 2535, street: "Av. Rivadavia", location: "Once"},


{name: "La Saladita", number: 2623, street: "Bartolomé Mitre", location: "Once"},
{name: "La Paloma", number: 2766, street: "Bartolomé Mitre", location: "Once"},
{name: "Feria del Once", number: 2757, street: "Bartolomé Mitre", location: "Once"},
{name: "Central 11", number: 2734, street: "Bartolomé Mitre", location: "Once"},
{name: "El Gran Poder", number: 2737, street: "Bartolomé Mitre", location: "Once"},
{name: "La Reina de Mitre", number: 2715, street: "Bartolomé Mitre", location: "Once"},

{name: "Mega Compra Once", number: 160, street: "Castelli", location: "Once"},
{name: "centro pueurredón", number: 150, street: "Castelli", location: "Once"},
{name: "Feria Del Sol", number: 234, street: "Castelli", location: "Once"},
{name: "Vía Valeria", number: 265, street: "Castelli", location: "Once"},

{name: "Punto Once", number: 279, street: "Pueyrredón", location: "Once"},
{name: "Pueyrredón", number: 241, street: "Pueyrredón", location: "Once"},
{name: "Las Naciones", number: 123, street: "Pueyrredón", location: "Once"},
{name: "La Playa", number: 555, street: "Pueyrredón", location: "Once"},
{name: "La Gran America", number: 560, street: "Pueyrredón", location: "Once"},
{name: "La Playita", number: 562, street: "Pueyrredón", location: "Once"},
{name: "La Unión", number: 240, street: "Pueyrredón", location: "Once"},

{name: "Sarmiento II", number: 2833, street: "Sarmiento", location: "Once"},
{name: "La Unión", number: 2870, street: "Sarmiento", location: "Once"},

{name: "Pasteur", number: 277, street: "Pasteur", location: "Once"},

{name: "Once", number: 2348, street: "Av. Corrientes", location: "Once"},
{name: "Center One", number: 2461, street: "Av. Corrientes", location: "Once"},
{name: "Rambla Katalunia", number: 2478, street: "Av. Corrientes", location: "Once"},
{name: "Imperial", number: 2510, street: "Av. Corrientes", location: "Once"},
{name: "Siglo", number: 2564, street: "Av. Corrientes", location: "Once"},
{name: "Vía del Sol", number: 2582, street: "Av. Corrientes", location: "Once"},
{name: "La Juanita", number: 2769, street: "Av. Corrientes", location: "Once"},
{name: "Pasteur", number: 346, street: "Av. Corrientes", location: "Once"},
]

export default galeries